{
  "branches": ["main", "development", "staging", "pipeline-dev"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/npm", {
      "npmPublish": false
    }],
    ["@semantic-release/github"],
    ["@semantic-release/git", {
      "assets": ["package.json"],
      "message": "chore(Release): ${nextRelease.version}\n\n${nextRelease.notes}"
    }]
  ]
}
