{
  "branches": ["main", {"name": "development", "prerelease": true}, {"name": "staging", "prerelease": true}],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/npm", {
      "npmPublish": false
    }],
    ["@semantic-release/git", {
      "assets": ["package.json"],
      "message": "chore(Release): ${nextRelease.version}\n\n${nextRelease.notes}"
    }]
  ]
}
