# Dockerfile to build server and client parts
FROM node:lts-alpine3.19 as build
WORKDIR /usr/src/app
COPY . .
RUN npm install
RUN npm run aas-portal:build

FROM nginx:latest as aas-portal
COPY --from=build /usr/src/app/projects/aas-portal/dist/browser/ /usr/share/nginx/html/
COPY --from=build /usr/src/app/projects/aas-portal/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
