services:
  aasportal-users:
    image: mongo
    container_name: aasportal-users
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=aasportal-users

  aasportal-index:
    image: mariadb
    container_name: aasportal-index
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    volumes:
      - ./projects/aasportal-index/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - sqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: aas-index
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  aasportal-cloud-db:
    image: mariadb
    container_name: aasportal-cloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  aasportal-cloud:
    image: nextcloud
    container_name: aasportal-cloud
    restart: always
    ports:
      - 8080:80
    links:
      - aasportal-cloud-db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=aasportal-cloud-db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}

  aas-server:
    container_name: aas-server
    build:
      context: .
      dockerfile: ./Dockerfile.aas-server
    environment:
      - USER_STORAGE=${USER_STORAGE}
      - AAS_INDEX=${AAS_INDEX}
      - TEMPLATE_STORAGE=${TEMPLATE_STORAGE}
    ports:
      - 1337:1337
  
  aas-portal:
    container_name: aas-portal
    build:
      context: .
      dockerfile: ./Dockerfile.aas-portal
    restart: always
    ports:
      - 80:80

volumes:
  mongodata:
  sqldata:
  nextcloud_db:
  nextcloud: