version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: AASPortalIndex
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"